version: '3'

services:
  api:
    # build:
    #   context: .
    #   dockerfile: Dockerfile
    build: .
    image: skl-nodejs
    ports:
      - "8080:8080"
    environment:
      - PG_DB=testdb
      - PG_USER=postgres
      - PG_PASSWORD=123
      - PG_HOST=postgres
    depends_on:
      - postgres
    networks:
      - private

  postgres:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: testdb
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - private

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    networks:
      - public
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api

networks:
  public:
    driver: bridge
  private:
    driver: bridge

volumes:
  nginx-conf:
  postgres-data:
