apiVersion: v1
kind: Pod
metadata:
  name: client-util
  namespace: "staging"
  labels:
    name: client-util
spec:
  containers:
    - name: client-util
      image: piyachet/client-util:1.0
      stdin: true
      tty: true
      imagePullPolicy: Always
      resources:
        requests:
          memory: 100Mi
          cpu: 10m
        limits:
          memory: 500Mi
          cpu: 100m
